version: "3.8"

services:
  medusa:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
      - postgres
    command: npm run dev

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: medusa_user
      POSTGRES_PASSWORD: Vinay123
      POSTGRES_DB: medusa_my_medusa_store
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  redis-data:
  pgdata:


# version: "3.8"

# services:
#   medusa:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "9000:9000"
#     env_file:
#       - .env
#     volumes:
#       - .:/app
#       - /app/node_modules
#     depends_on:
#       - redis
#     command: npm run dev

#   redis:
#     image: redis:7.0
#     ports:
#       - "6379:6379"
#     volumes:
#       - redis-data:/data

# volumes:
#   redis-data: